apiVersion: v1
kind: Pod
metadata:
 name: mongodb
spec:
 containers:
  - image: mongo
    name: mongodb
    ports:
      - containerPort: 27017
        protocol: TCP
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db2
 volumes:
  - name: mongodb-data
    hostPath: 
      path: /data/db2/mydb2
      type: DirectoryOrCreate